version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/rp-api
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/build.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/reload_server.sh
      timeout: 300
      runas: root
