name: Lint

on:
    push:
<<<<<<< HEAD
        branches:
            - "main"
            - "dev**"
    pull_request:
        branches:
            - "main"
=======
>>>>>>> main

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "18.x"
<<<<<<< HEAD
            - name: Install dependencies
              run: yarn
            - name: Run ESLint
              run: npx eslint .
=======
                  cache: "yarn"
            - name: Install dependencies
              run: yarn
            - name: Run ESLint
              run: npx eslint .
>>>>>>> main
